### PR TITLE
Added optional destructure

### PR DESCRIPTION
**Pull request by ShayBox**
Moved the function into an object to allow for destructing
Added example of destructing

### CODE REVIEW

**Comment by fisker** [comment]
it's not a good idea to export a  object rather than a simple  function.

even  
```
sync.sync = sync
module.exports = sync
```
is  better

**Comment by ShayBox** [comment]
That works too, whatever you prefer as long as you can do `const { sync } = require("promise-synchromizer")`

**Comment by fisker** [comment]
promise-synchronizer will only export a function. 

can't see any bad.

 sorry

**Comment by fisker** [comment]
feel free to publish your own npm package.

i'm closing this pr.

**Pull request closed without merging**
